jpeg_recompress:
  dry_run: false
  src_dir: /Users/csjune/Downloads
  dest_dir: /Users/csjune/jpgjpg/cnv
  bak_dir: /Users/csjune/jpgjpg/bak
  batch_count: 1000
  tmp_dir: /Users/csjune/jpgjpg/tmp
  active_start: '02:00' # in 24-hours
  active_for: 1 # hours
