jpeg_recompress:
  dry_run: true
  src_dir: /home/ubuntu/다운로드/assets
  dest_dir: /home/ubuntu/다운로드/converted
  thread_count: 4
  batch_count: 1000
  tmp_dir: /mnt/ram
  before: 2016-08-20
  after: 2000-01-01