source 'https://rubygems.org'

gem 'aws-sdk'
gem 'bugsnag'
gem 'byebug'
gem 'colorize'
gem 'concurrent-ruby'
gem 'facter'
gem 'filesize'
gem 'jimson'
gem 'parallel'
gem 'rake'
gem 'rx'
gem 'semantic_logger'
gem 'sqlite3'

gem 'nuvo-image', git: 'https://github.com/crema/nuvo-image'
